### PR TITLE
Create Musicalbum class

### PR DESCRIPTION
**Pull request by MNisarAli**
### 📝 Summary:

This pull request includes the implementation of the `MusicAlbum` class with an association to the `Item` class, the constructor method for setting up `MusicAlbum` class properties, and the `can_be_archived?()` method that returns true if the parent's method returns true AND if `on_spotify` equals true.

### 📋 Changes Made:

- [x]  Created `MusicAlbum` class associated with the `Item` class.
- [x]  Implemented the `constructor` method to define and set up `MusicAlbum` class properties.
- [x]  Implemented the `can_be_archived?()` method.

### Please review and provide feedback. Thank you! 😊🚀

### CODE REVIEW

**Comment by monicah79** [comment]
My lights are off again I haven't been in a position to complete the review
am sorry...Yasin kindly review this pull request

**Review by AbdifatahYasin1 — CHANGES_REQUESTED** [review]
@MNisarAli  You did a great job 🎉🎊

### Suggestions

- All MusicAlbum and Genre data should be preserved by saving collections in separate .json files.
- Create a schema.sql file with tables that will be analogical to the structure of the classes that you created:
music_albums table (add all properties and associations from the parent Item class as table columns)
genres table

- The following options should be available:

- List all music albums
- List all genres (e.g 'Comedy', 'Thriller')
- Add a music album

**Comment by MNisarAli** [comment]
Hi @AbdifatahYasin1, Please review the pull request summary along with the corresponding issue descriptions that I have linked to it. Additionally, note that I will address your suggested changes and other project requirements once I begin working on the remaining issues. Each project requirement will be submitted through separate pull requests, and I will include a link to the corresponding issue to which the pull request pertains.

**Review by AbdifatahYasin1 — APPROVED** [review]
@MNisarAli  Your project is complete 💥

**Pull request merged**
